# Generated by Django 5.1.4 on 2024-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("chest", models.FloatField()),
                ("waist", models.FloatField()),
                ("thigh", models.FloatField()),
                ("goal", models.CharField(max_length=100)),
                ("period", models.PositiveIntegerField()),
            ],
        ),
    ]
