# Generated by Django 5.1.4 on 2025-01-13 07:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="커뮤니터 제목", max_length=100)),
                ("description", models.TextField(help_text="커뮤니티 내용")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Fitplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "weight",
                    models.FloatField(
                        help_text="단위: kg",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "target_weight",
                    models.FloatField(
                        default=0.0,
                        help_text="목표 체중 (단위: kg)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "chest",
                    models.FloatField(
                        help_text="단위: 인치",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "waist",
                    models.FloatField(
                        help_text="단위: 인치",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "thigh",
                    models.FloatField(
                        help_text="단위: 인치",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(help_text="목표 달성 기간 (일)"),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.CharField(max_length=100)),
            ],
        ),
    ]
