# Generated by Django 5.1.4 on 2024-12-29 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitplans", "0013_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
